---
title: "data_prep"
author: "pmcdevitt"
date: "5 août 2017"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)


rm(list=ls())

library(ggplot2)

home_dir <- "~/_smu/_src/blr_prj3/"
setwd(home_dir)

data_dir <- "./data"

``````{r read data, include = TRUE, message = FALSE}

	setwd(home_dir)
	setwd(data_dir)

	homes <- read.csv("train.csv", stringsAsFactors = FALSE)
	setwd(home_dir)

	names(homes) <- tolower(names(homes))
	
	for (i in 2:(length(homes)))
	{
		if (class(homes[,i]) == "character")
		{
			homes[,i] <- factor (homes[,i])
		}
	}
```

```{r remove outliers, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	remove outliers ... more than 5 sigma from mean value
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
	lst <- length(homes) - 1	# sale price is (currently) last column
	
	for (i in 2 : lst)
	{
		if(class(homes[,i]) == "integer" || class(homes[,i]) == "numeric")
		{
			homes[,i][which(scale(homes[,i]) > 5)] <- NA
			homes[,i][which(scale(homes[,i]) < -5)] <- NA
		}
	}

```



```{r read data, include = TRUE, message = FALSE}

	setwd(home_dir)
	setwd(data_dir)

	shots <- read.csv("data.csv", stringsAsFactors = FALSE)
	setwd(home_dir)

	names(shots) <- tolower(names(shots))
	
	for (i in 2:(length(shots)))
	{
		if (class(shots[,i]) == "character")
		{
			shots[,i] <- factor (shots[,i])
		}
	}
```

```{r remove outliers, include = TRUE, message = FALSE}

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	remove outliers ... more than 5 sigma from mean value
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	
	lst <- length(shots) - 1	# sale price is (currently) last column
	
	for (i in 2 : lst)
	{
		if(class(shots[,i]) == "integer" || class(shots[,i]) == "numeric")
		{
			shots[,i][which(scale(shots[,i]) > 5)] <- NA
			shots[,i][which(scale(shots[,i]) < -5)] <- NA
		}
	}

```
